### ISSUE TITLE
M5 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_04_anh_eve#60]
Great App! I like a very clean layout and color scheme

Noticed some issue:
![image](https://user-images.githubusercontent.com/54612866/78272662-ac373c80-74c2-11ea-8ad5-86947607d1c6.png)

- Very hard to understand that the thing below graph 1 is a slider 
- Dates disappear from the graph when I select the slider
- 2nd plot should don't have abbreviated x-axis labels ( e.g AH)

Suggestion:
- I think plots 1 and 3 should be close to each other ( maybe side by side)? Cause they both show the date and are controlled by the first dropdown
-wider dropdown?:  cause your options are long, so they get cut down, and as a result, it does not look very nice. Maybe simplify the labels ( e.g.  just use "Tin oxide")
- May be things like "Plot 1 shows the variation" should not go into the header? but instead, be added as graph annotations?
- I would add more info about why you separated Pollutant and Weather variables?

**Comment by Anh-NguyetLe** [comment]
Fixes: 

- Header is now including motivation and the research question.
- We have added description of the plots, drop-downs as well as the instruction for the slider in the sidebar. The dates shouldn't disappear in the x-axis when slider is selected. However, if the range is less than a month, the label in the x-axis wont be showing since it is monthly. Hovering the mouse on the graph should still show detailed information including the recorded date of each data point. 

<img width="855" alt="Screen Shot 2020-04-06 at 7 03 26 AM" src="https://user-images.githubusercontent.com/51495301/78566909-be6fee00-77d4-11ea-8800-23ab78db933c.png">

- 2nd plot has now have proper axis label.
- Tabs are added so that plot 1 & 3 are now displaying together, plot 2 is now in a separate tab.
-  We separated the Pollutant and Weather variables simply because of logistic issue. We cannot display two axes on one graph on dash. Otherwise, there will be scaling problem with the discrepancy in units between those of the weather variables and those of the pollutants.
